// Generated by CoffeeScript 1.9.3

/*
Send badges to model to be saved
 */

(function() {
  var _, model;

  _ = require('underscore');

  model = require('../models/badges');

  exports.save = function(req, res, next) {
    var badges;
    badges = _.clone(req.body);
    return model.save(badges, function(err) {
      if (err) {
        return res.json(503, {
          error: true
        });
      } else {
        next();
        return model.trim();
      }
    });
  };

  exports.send = function(req, res, next) {
    var badges;
    badges = _.clone(req.body);
    return model.send(badges, function(err) {
      if (err) {
        return res.json(503, {
          error: true
        });
      }
      return res.json(200, {
        error: null
      });
    });
  };

  exports.get = function(req, res, next) {
    return model.get(function(err, data) {
      if (err) {
        return res.json(503, {
          error: true
        });
      }
      return res.json(200, data);
    });
  };

}).call(this);
