// Generated by CoffeeScript 1.9.3

/*
Send badges to model to be saved
 */

(function() {
  var _, model;

  _ = require('underscore');

  model = require('../models/badges');

  module.exports.save = function(req, res, next) {
    var badges;
    badges = _.clone(req.body);
    return model.save(badges, function(err) {
      if (err) {
        return res.json(503, {
          error: true
        });
      } else {
        return next();
      }
    });
  };

  module.exports.send = function(req, res, next) {};

}).call(this);
