// Generated by CoffeeScript 1.9.3
(function() {
  var axon, socket;

  axon = require('axon');

  socket = axon.socket('pub');

  socket.bind(3001);

  exports.send = function(badge) {
    return socket.send(badge);
  };

}).call(this);
