// Generated by CoffeeScript 1.9.3
(function() {
  var redis;

  redis = require('../lib/redis');

  exports.save = function(badges, callback) {
    var badge;
    if (!badges.length) {
      return callback(null, null);
    }
    badge = badges.pop();
    return redis.lpush('badges', JSON.stringify(badge), function(err) {
      if (err) {
        return callback(err, null);
      } else {
        return exports.save(badges, callback);
      }
    });
  };

}).call(this);
